### ISSUE TITLE
Include documentation about the fork from bitcoinj

### ISSUE THREAD

**Issue by hegjon** [bitcoinj-cash/bitcoinj#11]
Hi, it would be useful to know the history of the fork from bitcoinj, like is cash branched out from 0.14 or master?

**Comment by shadders** [comment]
It's branched from the 0.14.5 release of bitcoinj.  Releases under cash-<version> branch and new commits are placed in the cash branch.  Anything we backport from bitcoinj.org will go into the cash branch initially before it makes it into the next release branch.

**Comment by hegjon** [comment]
Thanks, got a bit confused, since there have been changes on master on bitcoinj that was not in the cash branch. For example the removal of orchid.

**Comment by Danconnolly** [comment]
Yes, we still need to merge in a bunch of commits from the master branch (bitcoinj) into the cash branch. Its on my to-do list.

Regards,
Daniel

-------- Original Message --------
