### ISSUE TITLE
wallet_tool - add option to skip use of checkpoints

### ISSUE THREAD

**Issue by Danconnolly** [bitcoinj-cash/bitcoinj#14]
When wallet_tool syncs the blockchain from scratch, it automatically uses checkpoints to skip ahead in the chain and sync faster.

However, for testing purposes, it would be nice to be able to skip this feature and sync from the beginning of the chain.

**Comment by HashEngineering** [comment]
For testing purposes, the BuildCheckpoints tool is also rather useful for verifying that the blockchain will sync.  DAA's can be verified.
