### ISSUE TITLE
Bitcoin ABC 0.17 May 15 upgrade

### ISSUE THREAD

**Issue by HashEngineering** [bitcoinj-cash/bitcoinj#32]
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes.md

At the MTP time of 1526400000 (Tue May 15 12:00:00 UTC, 2018) the following behaviors will change:

1. Increase the default datacarriersize to 220 byte at the MTP time of 1526400000
2. Increase the maximum blocksize to 32,000,000 bytes at the MTP time of 1526400000
3. Re-activate the following opcodes: OP_CAT, OP_AND, OP_OR, OP_XOR, OP_DIV, OP_MOD
4. Add the following new opcodes: OP_SPLIT to replace OP_SUBSTR, OP_NUM2BIN, OP_BIN2NUM

**Comment by shadders** [comment]
Hi hash,

I'm working on this already. So far discovered a few issues with our script
engine that leads me to believe it needs a complete rewrite sometime soon.
E.g. we don't enforce minimal encoding for numbers properly. No check
sequence verify support and a few script flags exist but are unused.

Hope to have a PR ready early next week.

WIP sans tests here:
https://github.com/shadders/bitcoinj-cash-dev/tree/monolith-activation

And here:
https://github.com/shadders/bitcoinj-cash-dev/tree/monolith-op-codes?files=1

**Comment by HashEngineering** [comment]
Ok, looking forward to what you come up with.

I am not sure if these will be breaking changes for bitcoinj-cash.
1.  Not sure what this is.
2.  In SPV mode with bloom filters, full blocks are not downloaded.  bitcoinj-cash doesn't have to check the size of blocks to see if they are valid sizes.

**Comment by Danconnolly** [comment]
The full pruned block stores don't like large blocks :-(

Collected Steve's work here: https://github.com/Danconnolly/bitcoinj-cash/tree/monolith

**Comment by HashEngineering** [comment]
I will try and take a look.

**Comment by HashEngineering** [comment]
When I run the tests, I get this error when running LevelDBFullPrunedBlockChainTest, while it passes with H2FullPrunedBlockChainTest.

```
java.lang.OutOfMemoryError: GC overhead limit exceeded

	at org.bitcoinj.script.Script.parse(Script.java:214)
	at org.bitcoinj.script.Script.<init>(Script.java:118)
	at org.bitcoinj.core.TransactionOutput.getScriptPubKey(TransactionOutput.java:116)
	at org.bitcoinj.core.Transaction.toString(Transaction.java:721)
	at org.bitcoinj.core.Transaction.toString(Transaction.java:638)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.bitcoinj.core.Block.toString(Block.java:496)
	at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:363)
	at org.bitcoinj.core.AbstractFullPrunedBlockChainTest.testGeneratedChain(AbstractFullPrunedBlockChainTest.java:92)
```

This may be a failure mode because I was running out of memory on my own machine.

@Danconnolly - what exception did you get with `AbstractFullPrunedBlockChainTest.testGeneratedChain`?

**Comment by Danconnolly** [comment]
I've pushed the code that we have so far to a new branch in this repo. The branch is called "monolith".

**Comment by rafa-js** [comment]
Hi all,

Good job with this, this is very important for the upgrade.

I've been thinking about the op_codes and the scripts implementation. There's a lot of switch blocks with many branches that contain big blocks. This approach isn't the best way to scale. 
Currently It's quite complicated, and the more time passes the less maintainable will be because Bitcoin Cash will enable more op_codes. 

Not necessarily before the update, but I would appreciate you to consider this approach.

- Encapsulate the details of each op_code in a different class. This class will contain the code of each switch branch.
- Following, the list of defined abstract concepts.
     - OpCode: defines the interface for the different op_codes.
     - ScriptExecutionContext: contains the shared variables and data structures required to execute a script.

A little bit more definition of the concepts, it would be required to define the details but:

```
class ScriptExecutionContext{

    private int opCount = 0;
    private int lastCodeSepLocation = 0;

    private LinkedList<byte[]> altstack = new LinkedList<byte[]>();
    private LinkedList<Boolean> ifStack = new LinkedList<Boolean>();

    // Getters and setter...

}

interface OpCode{

    boolean isEnabled();

    void execute(ScriptExecutionContext context) throws ScriptException;

}

interface IOpCodeFactory{

    OpCode getOpCode(ScriptChunk chunk);

}
```

And the `Script` class would look more like:

```
public class Script {
    public static void executeScript(@Nullable Transaction txContainingThis, long index,
                                     Script script, LinkedList<byte[]> stack, Coin value, Set<VerifyFlag> verifyFlags) throws ScriptException {
        ScriptExecutionContext context = new ScriptExecutionContext();
        for (ScriptChunk chunk : script.chunks) {
            opCodesFactory.getOpCode(chunk).execute(context);
        }
    }
}
```

Comments?

Btw, let me know if I can help for your current implementation.
