### ISSUE TITLE
i use seedCode import Wallet But the blance is 0.00

### ISSUE THREAD

**Issue by fastener** [bitcoinj-cash/bitcoinj#34]
String seedCode = "xxxx xxxx xxx xxx";
        long creationtime = 1524106204;
        DeterministicSeed seed = null;
		try {
			seed = new DeterministicSeed(seedCode, null, "", creationtime);
		} catch (UnreadableWalletException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        wallet = Wallet.fromSeed(params, seed);
wallet.getBalance()  

I use the above code to import the wallet, get the balance of the wallet, but the balance of the wallet is empty, and the address of this wallet is not 0 in the other purse tools. Why

**Comment by HashEngineering** [comment]
What is your code that connects to the blockchain?  That is required to know there is a balance.

**Comment by fastener** [comment]
NetworkParameters params  =MainNetParams.get()
I use the above code to get the link master network，
Then the balance that is viewed with Electron-Cash is valuable
But the account balance in the above code is 0

**Comment by fastener** [comment]
警告: Hashes: null vs 000000000000000000408e0441cd2cc9a6aa0a314e6bb596622c52ad1c2901f4
Start peer group
Apr 19, 2018 4:23:42 PM org.bitcoinj.core.PeerGroup$8 run
信息: Starting ...
Downloading block chain
Apr 19, 2018 4:23:42 PM org.bitcoinj.core.PeerGroup maybeCheckForLocalhostPeer
信息: Localhost peer not detected.
Apr 19, 2018 4:23:47 PM org.bitcoinj.net.discovery.MultiplexingDiscovery getPeers
警告: Seed seed-abc.bitcoinforks.org: failed to look up: org.bitcoinj.net.discovery.PeerDiscoveryException: java.net.UnknownHostException: seed-abc.bitcoinforks.org: nodename nor servname provided, or not known
Apr 19, 2018 4:23:47 PM org.bitcoinj.net.discovery.MultiplexingDiscovery getPeers
警告: Seed seeder.criptolayer.net: timed out
Apr 19, 2018 4:23:47 PM org.bitcoinj.core.PeerGroup discoverPeers

**Comment by HashEngineering** [comment]
What is the account path that Electron-cash uses?  If it is BIP44 (m/44'/'00) then you won't get the correct balance with bitcoinj-cash which uses BIP32 (m/0').  If you want it to match BIP44, then you will need to create your own DeterministicKeyChain with an account path matching Electron-Cash.
