### ISSUE TITLE
What does Fast catchup is incompatible with fully verifying mean?

### ISSUE THREAD

**Issue by fastener** [bitcoinj-cash/bitcoinj#37]
public class MyWalletAppKit extends WalletAppKit {

	public MyWalletAppKit(Context context, File directory, String filePrefix) {
		super(context, directory, filePrefix);
		// TODO Auto-generated constructor stub
	}

	public MyWalletAppKit(NetworkParameters params, File file, String filePrefix) {
		
		super(params, file, filePrefix);
	}

	@Override
	protected void onSetupCompleted() {
		if (wallet().getKeyChainGroupSize() < 1) {
			ECKey eckey= new  ECKey();
			wallet().importKey(eckey);

		}
		peerGroup().addPeerDiscovery(new DnsDiscovery(this.params));
		peerGroup().setMinBroadcastConnections(8);
		peerGroup().setMaxConnections(10);
		peerGroup().setFastCatchupTimeSecs(wallet().getEarliestKeyCreationTime());
		System.out.println("wallet address:"+wallet().currentReceiveAddress()+" wallet "+wallet().toString());
	}

	@Override
	protected PeerGroup createPeerGroup() throws TimeoutException {
		// TODO Auto-generated method stub
		PeerGroup peerGroup = null;
		try {
			FullPrunedBlockStore store = new H2FullPrunedBlockStore(this.params, "bch_test9", 1000);
			FullPrunedBlockChain vChain = new FullPrunedBlockChain(this.params, store);
			peerGroup = new PeerGroup(this.params, vChain);
		
//			super.peerGroup()
			
			// peerGroup.downloadBlockChain();
		} catch (BlockStoreException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("peergroup error" + e);
		}

		return peerGroup;
	}

	
	

}

When I Override the createPeerGroup method, I use the new H2FullPrunedBlockStore and then use peerGroup ().SetFastCatchupTimeSecs ().SetFastCatchupTimeSecs (wallet ().GetEarliestKeyCreationTime ()); the system will throw the Fast catchup is incompatible with exception. ImeSecs

**Comment by HashEngineering** [comment]
Fast catch up is for SPV.  Since you are using a full block store, then there is no use for checkpoints or fast catch up.
