### ISSUE TITLE
Proposal to remove bitcoinj (BTC) branches from this repo

### ISSUE THREAD

**Issue by Danconnolly** [bitcoinj-cash/bitcoinj#50]
I propose to remove the BTC Bitcoinj branches from this repo because they cause confusion. If we need to merge changes from the BTC Bitcoinj into this repo, this can be done using a local git, pulling the necessary commits across.

The affected branches would be: "master", "release-0.14", and "segwit".

Any thoughts?

**Comment by HashEngineering** [comment]
Agree to remove them.  If we need anything from them we can get it from upstream.

**Comment by rafa-js** [comment]
This was going to happen at some point. I agree.

**Comment by Danconnolly** [comment]
Done.
