### ISSUE TITLE
Transaction Rejected for Signature must use SIGHASH_FORKID even when using request.setUseForkId(true)

### ISSUE THREAD

**Issue by babramovitch** [bitcoinj-cash/bitcoinj#54]
I'm trying to send a test transaction using Android / Kotlin, and encountered the SIGHASH_FORKID error, but even after using request.setForkId(True) it still doesn't work?  Not sure whats going on?

Everything I find out there just says set the flag?

Received Reject: tx for reason 'mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)' (16)

```
fun send() {
        val recipientAddress = "someAddress"
        val amount = "0.00001"
        val request =
            SendRequest.to(Address.fromBase58(MainNetParams.get(), recipientAddress), Coin.parseCoin(amount))
     
        request.setUseForkId(true)

        request.feePerKb = Coin.valueOf(1000)

        try {
            kit.wallet().sendCoins(request)
        } catch (e: InsufficientMoneyException) {
            e.printStackTrace()
            Log.i("TAG", "Error")
        }
}
```

**Comment by babramovitch** [comment]
I ended up copying my seed, uninstalling the app, and restoring from seed, and it now works.

My best guess is the failed transaction before I set the flag kept trying to send instead of my newest one, and the newest one never actually tried to send?

Maybe this will help anyone else who encounters this issue

**Comment by HashEngineering** [comment]
Yes, the failed transaction would stay in the wallet file and attempted to be resent every time the PeerGroup 
 or app was restarted.

**Comment by babramovitch** [comment]
Cool, thanks for the confirmation =)
