### ISSUE TITLE
Cannot send transaction

### ISSUE THREAD

**Issue by sparr0w7** [bitcoinj-cash/bitcoinj#56]
This is the code that I made. Is there anything to correct?

`public void send(String toAddress , String amount)`
`{`
    ` try {`
            ` SendRequest request = SendRequest.to(Address.fromBase58(getMainNetNetwork(), toAddress), Coin.parseCoin(amount));`
            ` kit.wallet().completeTx(request);`
            ` kit.wallet().commitTx(request.tx);`
            ` kit.peerGroup().broadcastTransaction(request.tx).broadcast();`
        `} catch (InsufficientMoneyException e) {`
              ` e.printStackTrace();`
        ` }`
   `  }`

**Comment by HashEngineering** [comment]
See #4 , first few comments.

**Comment by sparr0w7** [comment]
SendRequest.setUseForkId(true) <--- **added code???**

`SendRequest request = SendRequest.to(Address.fromBase58(getMainNetNetwork(), toAddress), Coin.parseCoin(amount));`
              ` request.setUseForkId(true);`


I speak a very basic level of English. Sorry

**Comment by HashEngineering** [comment]
Yes, that is the answer.

**Comment by sparr0w7** [comment]
Thank you a lot :)

**Comment by HashEngineering** [comment]
Great, we will count this issue as closed.
