### ISSUE TITLE
"Install failed with no matching ABIs" on Android Studio 3.1.3 due to lambdaworks Scrypt

### ISSUE THREAD

**Issue by gcbrown** [bitcoinj-cash/bitcoinj#61]
I've been working on a small project with bitcoinj cash (great work by the way). Recently I tried to build it and got this error:

INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

I found this post on stackoverflow dealing with a previous version of bitcoinj:

https://stackoverflow.com/questions/28560096/bitcoinj-will-not-compile-onto-nexus-5-with-android-studio/28924959#28924959

In this issue, excluding the 'scrypt' module from bitcoinj got rid of this error, and it also worked for me. I'm interested if anyone else has this issue building for Android, and how they fixed it. In the post, they recommend switching to org.spongycastle.crypto.generators.SCrypt. If there's an easier way to fix this, that's great, but it might be worth looking into migrating to spongycastle's implementation.

**Comment by HashEngineering** [comment]
On my android app, I don't have this issue.

https://github.com/bitcoincash-wallet/bitcoincash-wallet/blob/master/wallet/build.gradle

On my app, I actually build the native libraries as part of the build process, but checkout the "exclude" statements in the build.gradle

**Comment by gcbrown** [comment]
How did you determine what to exclude? I'd rather not exclude the whole Scrypt module, it seems like you're excluding smaller parts of it.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by HashEngineering** [comment]
How do we know?  Basically from copying what was in the original bitcoin-wallet code.  They figured it out years earlier.

**Comment by gcbrown** [comment]
I've got it working using your link. Thanks for the help.
